/*
 * MIDICVX Audio Bootloader 1.0 RC
 *
 * ATmega328 / ATmega328P, 16 MHz
 * Boot section: 0x7000..0x7FFF (4 KiB)
 * Update input: CLOCK jack -> PC1 / ADC1
 * Entry: hold PROGRAM during reset/power-up. If a valid application exists and
 * no update audio is detected for ~3 seconds, control falls through to the
 * application so the original PROGRAM-at-power-up calibration remains usable.
 *
 * Audio protocol is generated by make_update_wav.py. It is edge-interval
 * encoded and decoded through the ADC, allowing sub-logic-level audio signals
 * to be detected. Every 128-byte flash page has its own CRC16. The complete
 * application is verified with CRC32 before it is marked bootable.
 */
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/boot.h>
#include <avr/eeprom.h>
#include <avr/pgmspace.h>
#include <avr/wdt.h>
#include <util/delay.h>
#include <stdint.h>

#define APP_LIMIT_BYTES        0x7000U
#define UPDATE_ADC_CHANNEL     1U          /* PC1 / ADC1 / CLOCK jack */
#define BUTTON_PIN_MASK        _BV(PC5)    /* active low */
#define STATUS_LED_MASK        _BV(PC3)    /* lower red */
#define GATE1_MASK             _BV(PC2)
#define GATE2_MASK             _BV(PC4)

#define PROTOCOL_VERSION       1U
#define PACKET_MANIFEST        0x10U
#define PACKET_DATA            0x20U
#define PACKET_END             0x30U
#define DATA_CHUNK_SIZE        32U
#define MAX_PACKET_DATA        DATA_CHUNK_SIZE

/* Timer1 runs at F_CPU/8 = 2 MHz, 0.5 us/tick. */
#define PREAMBLE_MIN_TICKS     160U   /* 80 us */
#define PREAMBLE_MAX_TICKS     360U   /* 180 us */
#define SYNC_MIN_TICKS        3200U   /* 1.6 ms */
#define BIT_ZERO_ONE_TICKS     750U   /* threshold between 250/500 us */
#define BIT_MIN_TICKS          350U
#define BIT_MAX_TICKS         1250U
#define EDGE_TIMEOUT_TICKS    6000U   /* 3 ms */
#define MIN_PREAMBLE_EDGES       20U
#define MIN_ADC_RANGE              6U

/* EEPROM byte is intentionally separate from the application settings block.
 * 0xA5 = application safe to boot, 0x42 = update started/not yet verified.
 * Any other non-erased value is treated conservatively as recovery mode. */
#define EEPROM_BOOT_STATUS_ADDR  96U
#define EEPROM_PAGE_COUNT_LO      97U
#define EEPROM_PAGE_COUNT_HI      98U
#define EEPROM_FIRST_PKT_TYPE     99U
#define EEPROM_FIRST_PKT_SEQ_LO  100U
#define EEPROM_FIRST_PKT_SEQ_HI  101U
#define BOOT_STATUS_VALID        0xA5U
#define BOOT_STATUS_UPDATING     0x42U

static uint8_t adc_low_threshold;
static uint8_t adc_high_threshold;
static uint8_t signal_level;
static uint16_t expected_sequence;
static uint16_t manifest_size;
static uint32_t manifest_crc32;
static uint8_t update_active;
static uint8_t page_buffer[SPM_PAGESIZE];

static void jump_to_application(void) __attribute__((noreturn));

static void gates_safe(void)
{
    DDRC |= (GATE1_MASK | GATE2_MASK);
    PORTC &= (uint8_t)~(GATE1_MASK | GATE2_MASK);
}

/* All LEDs are used while the bootloader is active. */
#define BOOT_LED_MASK   (STATUS_LED_MASK | GATE1_MASK | GATE2_MASK)

static void status_on(void)
{
    PORTC |= BOOT_LED_MASK;
}

static void status_off(void)
{
    PORTC &= (uint8_t)~BOOT_LED_MASK;
}


static void status_success(void)
{
    status_on();
    _delay_ms(1000);
    status_off();
}

static void status_error(void)
{
    for(;;) {
        status_on();
        _delay_ms(125);
        status_off();
        _delay_ms(125);
    }
}

static void io_init(void)
{
    gates_safe();

    DDRC &= (uint8_t)~BUTTON_PIN_MASK;
    PORTC |= BUTTON_PIN_MASK;

    DDRC |= STATUS_LED_MASK;
    status_off();

    /* ADC1 input, no pull-up, digital input disabled. */
    DDRC &= (uint8_t)~_BV(PC1);
    PORTC &= (uint8_t)~_BV(PC1);
    DIDR0 |= _BV(ADC1D);
}

static uint8_t program_button_held(void)
{
    return ((PINC & BUTTON_PIN_MASK) == 0U);
}

static void adc_init(void)
{
    /* AVcc reference, left-adjusted result, ADC1. ADC clock = 500 kHz. */
    ADMUX = _BV(REFS0) | _BV(ADLAR) | UPDATE_ADC_CHANNEL;
    ADCSRA = _BV(ADEN) | _BV(ADPS2) | _BV(ADPS0); /* /32 */
}

static uint8_t adc_read8(void)
{
    ADCSRA |= _BV(ADSC);
    while((ADCSRA & _BV(ADSC)) != 0U) { }
    return ADCH;
}

static void timer_init(void)
{
    TCCR1A = 0U;
    TCCR1B = _BV(CS11); /* /8 */
    TCNT1 = 0U;
}

static uint8_t application_present(void)
{
    uint16_t reset_word = pgm_read_word((const void *)0x0000U);
    return (reset_word != 0xFFFFU && reset_word != 0x0000U);
}

static void jump_to_application(void)
{
    void (*app)(void) = (void (*)(void))0x0000;
    cli();
    ADCSRA = 0U;
    TCCR1B = 0U;
    status_off();
    gates_safe();
    wdt_disable();
    app();
    for(;;) { }
}

/* Search ~5 ms ADC windows until a useful audio range is seen. timeout_windows
 * is ignored in forced recovery mode when set to zero. */
static uint8_t calibrate_audio(uint8_t timeout_windows)
{
    uint8_t windows = 0U;
    for(;;) {
        uint16_t samples;
        uint8_t lo = 0xFFU;
        uint8_t hi = 0U;

        for(samples = 0U; samples < 192U; ++samples) {
            uint8_t v = adc_read8();
            if(v < lo) lo = v;
            if(v > hi) hi = v;
        }

        if((uint8_t)(hi - lo) >= MIN_ADC_RANGE) {
            uint8_t span = (uint8_t)(hi - lo);
            adc_low_threshold = (uint8_t)(lo + (span >> 2));
            adc_high_threshold = (uint8_t)(hi - (span >> 2));
            signal_level = (adc_read8() >= (uint8_t)((lo + hi) >> 1)) ? 1U : 0U;
            return 1U;
        }

        if(timeout_windows != 0U && ++windows >= timeout_windows)
            return 0U;
    }
}

/* Wait for one hysteretic audio edge. Timer1 is reset on every accepted edge
 * and the edge-to-edge interval is returned in ticks. */
static uint8_t wait_edge(uint16_t timeout_ticks, uint16_t *ticks)
{
    TCNT1 = 0U;
    for(;;) {
        uint8_t v = adc_read8();
        if(signal_level == 0U) {
            if(v >= adc_high_threshold) {
                signal_level = 1U;
                *ticks = TCNT1;
                return 1U;
            }
        } else {
            if(v <= adc_low_threshold) {
                signal_level = 0U;
                *ticks = TCNT1;
                return 1U;
            }
        }

        if(TCNT1 >= timeout_ticks)
            return 0U;
    }
}

static uint8_t wait_packet_sync(void)
{
    uint8_t preamble = 0U;
    uint16_t dt;
    uint8_t heartbeat = 0U;

    for(;;) {
        if(!wait_edge(30000U, &dt)) {
            preamble = 0U;

            /*
             * No audio edge detected.
             * Toggle the status LED periodically so it is obvious
             * that the bootloader is alive and waiting.
             */
            if(++heartbeat >= 16U) {
                PORTC ^= STATUS_LED_MASK;
                heartbeat = 0U;
            }

            continue;
        }

        /* Audio activity: keep status LED on while looking for sync. */
        PORTC |= STATUS_LED_MASK;
        heartbeat = 0U;

        if(dt >= PREAMBLE_MIN_TICKS && dt <= PREAMBLE_MAX_TICKS) {
            if(preamble < 0xFFU) ++preamble;
            continue;
        }

        if(dt >= SYNC_MIN_TICKS && preamble >= MIN_PREAMBLE_EDGES) {
            /* This long-gap edge is the packet start marker. */
            return 1U;
        }

        preamble = 0U;
    }
}

static uint8_t receive_bit(uint8_t *bit)
{
    uint16_t dt;
    if(!wait_edge(EDGE_TIMEOUT_TICKS, &dt)) return 0U;
    if(dt < BIT_MIN_TICKS || dt > BIT_MAX_TICKS) return 0U;
    *bit = (dt >= BIT_ZERO_ONE_TICKS) ? 1U : 0U;
    return 1U;
}

static uint8_t receive_byte(uint8_t *value)
{
    uint8_t i;
    uint8_t v = 0U;
    for(i = 0U; i < 8U; ++i) {
        uint8_t bit;
        if(!receive_bit(&bit)) return 0U;
        v |= (uint8_t)(bit << i); /* LSB first */
    }
    *value = v;
    return 1U;
}

static uint16_t crc16_update(uint16_t crc, uint8_t data)
{
    uint8_t i;
    crc ^= (uint16_t)data << 8;
    for(i = 0U; i < 8U; ++i)
        crc = (crc & 0x8000U) ? (uint16_t)((crc << 1) ^ 0x1021U) : (uint16_t)(crc << 1);
    return crc;
}

static uint32_t crc32_update(uint32_t crc, uint8_t data)
{
    uint8_t i;
    crc ^= data;
    for(i = 0U; i < 8U; ++i)
        crc = (crc & 1UL) ? ((crc >> 1) ^ 0xEDB88320UL) : (crc >> 1);
    return crc;
}

static uint32_t flash_crc32(uint16_t length)
{
    uint16_t address;
    uint32_t crc = 0xFFFFFFFFUL;
    for(address = 0U; address < length; ++address)
        crc = crc32_update(crc, pgm_read_byte((const void *)(uintptr_t)address));
    return crc ^ 0xFFFFFFFFUL;
}

static void write_flash_page(uint16_t page_address, const uint8_t *data, uint8_t length)
{
    uint16_t i;
    uint8_t sreg = SREG;
    cli();

    boot_page_erase(page_address);
    boot_spm_busy_wait();

    for(i = 0U; i < SPM_PAGESIZE; i += 2U) {
        uint8_t lo = (i < length) ? data[i] : 0xFFU;
        uint8_t hi = ((uint16_t)(i + 1U) < length) ? data[i + 1U] : 0xFFU;
        boot_page_fill((uint16_t)(page_address + i), (uint16_t)lo | ((uint16_t)hi << 8));
    }

    boot_page_write(page_address);
    boot_spm_busy_wait();
    boot_rww_enable();
    SREG = sreg;
}

static uint8_t receive_packet(uint8_t *type, uint16_t *sequence,
                              uint8_t *length, uint8_t *payload)
{
    uint8_t seq_lo, seq_hi, len, i, rx_crc_lo, rx_crc_hi;
    uint16_t crc = 0xFFFFU;

    if(!receive_byte(type)) return 0U;
    crc = crc16_update(crc, *type);
    if(!receive_byte(&seq_lo)) return 0U;
    crc = crc16_update(crc, seq_lo);
    if(!receive_byte(&seq_hi)) return 0U;
    crc = crc16_update(crc, seq_hi);
    *sequence = (uint16_t)seq_lo | ((uint16_t)seq_hi << 8);
    if(!receive_byte(&len)) return 0U;
    crc = crc16_update(crc, len);
    if(len > MAX_PACKET_DATA) return 0U;

    for(i = 0U; i < len; ++i) {
        if(!receive_byte(&payload[i])) return 0U;
        crc = crc16_update(crc, payload[i]);
    }

    if(!receive_byte(&rx_crc_lo) || !receive_byte(&rx_crc_hi)) return 0U;
    if(crc != ((uint16_t)rx_crc_lo | ((uint16_t)rx_crc_hi << 8))) return 0U;

    *length = len;
    return 1U;
}

static uint8_t parse_manifest(const uint8_t *p, uint8_t len)
{
    if(len != 14U) return 0U;
    if(p[0] != 'M' || p[1] != 'X' || p[2] != 'U' || p[3] != '1') return 0U;
    if(p[4] != PROTOCOL_VERSION) return 0U;

    manifest_size = (uint16_t)p[5] | ((uint16_t)p[6] << 8);
    manifest_crc32 = (uint32_t)p[7] |
                     ((uint32_t)p[8] << 8) |
                     ((uint32_t)p[9] << 16) |
                     ((uint32_t)p[10] << 24);

    if(manifest_size == 0U || manifest_size > APP_LIMIT_BYTES) return 0U;
    expected_sequence = 0U;
    update_active = 1U;
    eeprom_update_byte((uint8_t *)EEPROM_BOOT_STATUS_ADDR, BOOT_STATUS_UPDATING);
    eeprom_update_byte((uint8_t *)EEPROM_PAGE_COUNT_LO, 0U);
    eeprom_update_byte((uint8_t *)EEPROM_PAGE_COUNT_HI, 0U);
    return 1U;
}

static void reboot(void) __attribute__((noreturn));
static void reboot(void)
{
    cli();
    wdt_enable(WDTO_15MS);
    for(;;) { }
}

int main(void)
{
    uint8_t boot_status;
    uint8_t force_recovery;
    uint8_t payload[MAX_PACKET_DATA];

    MCUSR = 0U;
    wdt_disable();
    cli();
    io_init();
    adc_init();
    timer_init();
    _delay_ms(20);

    boot_status = eeprom_read_byte((const uint8_t *)EEPROM_BOOT_STATUS_ADDR);

    /* First boot after ISP installation: bless the already-present app. */
    if(boot_status == 0xFFU && application_present() && !program_button_held()) {
        eeprom_update_byte((uint8_t *)EEPROM_BOOT_STATUS_ADDR, BOOT_STATUS_VALID);
        jump_to_application();
    }

    force_recovery = (uint8_t)(boot_status != BOOT_STATUS_VALID || !application_present());

    if(!force_recovery && !program_button_held())
        jump_to_application();

    /* Bootloader ready. */
    status_on();

    /* Diagnostic: clear first-valid-packet record for this update attempt. */
    eeprom_update_byte((uint8_t *)EEPROM_FIRST_PKT_TYPE, 0xFFU);
    eeprom_update_byte((uint8_t *)EEPROM_FIRST_PKT_SEQ_LO, 0xFFU);
    eeprom_update_byte((uint8_t *)EEPROM_FIRST_PKT_SEQ_HI, 0xFFU);

    /* Boot behavior:
 *
 *  - Normal power-up: jump directly to the application.
 *  - PROGRAM held: wait forever for update audio.
 *  - Invalid application: recovery mode; wait forever.
 */
if (!program_button_held() && !force_recovery)
{
    jump_to_application();
}

calibrate_audio(0U);

    status_off();

    for(;;) {
        uint8_t type, length;
        uint16_t sequence;

        wait_packet_sync();

        /* Diagnostic: GATE1/yellow = packet sync detected. */
        PORTC |= GATE1_MASK;

        if(!receive_packet(&type, &sequence, &length, payload)) {
            /* Bad audio packet: discard it and resynchronize.
             * The WAV encoder transmits every packet twice. */
            status_on();
            _delay_ms(20);
            status_off();
            continue;
        }

        /* Diagnostic: GATE2/yellow = complete CRC-valid packet decoded. */
        PORTC |= GATE2_MASK;

        if(eeprom_read_byte((const uint8_t *)EEPROM_FIRST_PKT_TYPE) == 0xFFU) {
            eeprom_update_byte((uint8_t *)EEPROM_FIRST_PKT_TYPE, type);
            eeprom_update_byte((uint8_t *)EEPROM_FIRST_PKT_SEQ_LO,
                               (uint8_t)(sequence & 0xFFU));
            eeprom_update_byte((uint8_t *)EEPROM_FIRST_PKT_SEQ_HI,
                               (uint8_t)(sequence >> 8));
        }

        if(type == PACKET_MANIFEST) {
            if(!parse_manifest(payload, length)) {
                /* Ignore malformed manifest and wait for its repeated copy. */
                continue;
            }

            /* Diagnostic: both yellow LEDs = manifest accepted. */
            PORTC |= (GATE1_MASK | GATE2_MASK);
            _delay_ms(250);
            PORTC &= (uint8_t)~(GATE1_MASK | GATE2_MASK);
            continue;
        }

        if(type == PACKET_DATA) {
            uint16_t address;
            uint16_t expected_chunks;
            uint16_t page_base;
            uint8_t page_offset;
            uint8_t i;

            if(!update_active) {
                continue;
            }

            /*
             * Every audio packet is transmitted twice.
             * Ignore an already accepted duplicate.
             */
            if(sequence < expected_sequence) {
                continue;
            }

            /*
             * If this is ahead of the expected chunk, the expected
             * chunk was lost. Ignore this packet and wait for sync.
             */
            if(sequence > expected_sequence) {
                continue;
            }

            expected_chunks =
                (uint16_t)((manifest_size + DATA_CHUNK_SIZE - 1U) /
                           DATA_CHUNK_SIZE);

            address = (uint16_t)(sequence * DATA_CHUNK_SIZE);

            if(sequence >= expected_chunks ||
               address >= manifest_size ||
               length == 0U ||
               length > DATA_CHUNK_SIZE ||
               (uint16_t)(address + length) > manifest_size) {
                continue;
            }

            /* Every chunk except the final one must contain 32 bytes. */
            if(sequence + 1U < expected_chunks &&
               length != DATA_CHUNK_SIZE) {
                continue;
            }

            page_base =
                (uint16_t)(address & (uint16_t)~(SPM_PAGESIZE - 1U));
            page_offset = (uint8_t)(address & (SPM_PAGESIZE - 1U));

            /*
             * Beginning of a new AVR flash page:
             * erase our RAM assembly buffer to FF.
             */
            if(page_offset == 0U) {
                for(i = 0U; i < SPM_PAGESIZE; ++i) {
                    page_buffer[i] = 0xFFU;
                }
            }

            for(i = 0U; i < length; ++i) {
                page_buffer[(uint8_t)(page_offset + i)] = payload[i];
            }

            ++expected_sequence;

            /*
             * Program flash after four 32-byte chunks, or after the
             * final partial chunk of the application image.
             */
            if((uint16_t)(page_offset + length) >= SPM_PAGESIZE ||
               expected_sequence == expected_chunks) {

                write_flash_page(page_base,
                                 page_buffer,
                                 SPM_PAGESIZE);

                /* Diagnostic: completed AVR flash pages. */
                {
                    uint16_t completed_pages =
                        (uint16_t)(page_base / SPM_PAGESIZE) + 1U;

                    eeprom_update_byte(
                        (uint8_t *)EEPROM_PAGE_COUNT_LO,
                        (uint8_t)(completed_pages & 0xFFU));

                    eeprom_update_byte(
                        (uint8_t *)EEPROM_PAGE_COUNT_HI,
                        (uint8_t)(completed_pages >> 8));
                }

                status_on();
                _delay_ms(8);
                status_off();
            }

            continue;
        }

        if(type == PACKET_END) {
            uint16_t expected_chunks =
                (uint16_t)((manifest_size + DATA_CHUNK_SIZE - 1U) /
                           DATA_CHUNK_SIZE);

            if(!update_active || length != 0U ||
               sequence != expected_chunks ||
               expected_sequence != expected_chunks) {
                /* Ignore invalid/incomplete END and wait for repeated copy. */
                continue;
            }

            status_on();
            if(flash_crc32(manifest_size) == manifest_crc32) {
                eeprom_update_byte((uint8_t *)EEPROM_BOOT_STATUS_ADDR, BOOT_STATUS_VALID);
                status_off();
                status_success();
                reboot();
            }
            status_off();
            update_active = 0U;
            status_error();
            continue;
        }

        /* Unknown packet type: ignore and resynchronize. */
        continue;
    }
}
